### PR TITLE
Added name to group model + fixed plurality issue

### LINKED ISSUE #37: Add group name to group model
Group model should include a String for the group name to allow for group searching / group dropdown etc.

### PR DESCRIPTION
**Pull request by aidenszeto**
# Contributors

@aidenszeto 

# Relevant issue

Closes #37 

# Summary of change

 - Added `name` field to group model
 - Changed `Drift` array to `Drifts`
 - Added JSON bindings in group model
 - Added emacs autosave filename convention to gitignore

# Testing/Verification

N/A

### CODE REVIEW

**Comment by aidenszeto** [comment]
One thing we should discuss is whether or not we want to make `name` required - if we leave it optional, we could have it default to the names of the users in the group.

**Comment by teekenzie** [comment]
> One thing we should discuss is whether or not we want to make `name` required - if we leave it optional, we could have it default to the names of the users in the group.

I was just about to ask about the name being required. The issue with having it default to the names of the users is that the group could be created without any users and thus the name would be an empty string?
My take is that it should be required because people might create multiple new groups without users and they are all going to have the same name and is undifferentiable

**Comment by brandonLi8** [comment]
> I was just about to ask about the name being required. The issue with having it default to the names of the users is that the group could be created without any users and thus the name would be an empty string?

Currently, it's impossible to create a group without users (min=1 validator, and the group has to contain the user that created the group). So I think it's OK to default to the names of the users (messenger model), and we can do that in a separate ticket (update the create group route) as well. 

EDIT: But maybe it should be required for the model schema, and the route or the creating function can create the default name if necessary.

**Comment by teekenzie** [comment]
> Currently, it's impossible to create a group without users (min=1 validator, and the group has to contain the user that created the group). So I think it's OK to default to the names of the users (messenger model), and we can do that in a separate ticket (update the create group route) as well.

Consider that the users array is guaranteed to exist, we should update the array to set binding:"required" to also reflect that

**Comment by aidenszeto** [comment]
`name` will be required in Group model. Default name implementation will happen in #46

**Review by teekenzie — APPROVED** [review]

File: models/group_model.go [hunk 1]
```diff
@@ -7,20 +7,18 @@ import (
 
 type Group struct {
 	mgm.DefaultModel `bson:",inline"`
-	Users            []primitive.ObjectID `bson:"users"`
-	Drift            []primitive.ObjectID `bson:"drift"`
+	Name             string               `bson:"name" json:"name" binding:"required"`
+	Users            []primitive.ObjectID `bson:"users" json:"users" binding:"required"`
```
Comment (anjanbharadwaj) [inline models/group_model.go]: Not _completely_ necessary per se, since we have this check in group_controller's create route, but we could potentially add `min=1` to the Users field here as well, just in case (or maybe so in the future, if we support kicking members from a group, we can ensure that a group doesn't get completely nuked to 0 members). 

Regardless, its not a super important issue to handle right now so feel free to add it in if you want.

**Review by anjanbharadwaj — APPROVED** [review]
LGTM other than that one comment (optional though).
